# Linear Regression02

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import sklearn
# From sklearn import liner_model
# For train & test
from sklearn.model_selection import train_test_split
# From sklearn import liner_model
from sklearn.linear_model import LinearRegression


df = pd.read_csv("student-por.csv",sep=";")
df = df[["age","absences", "freetime", "Medu", "G1", "G2","G3"]]
predict = "G3"

X =np.array(df.drop([predict],axis =  1))
y = np.array(df[predict])
# The output of the method from 100% randomizely  and put here 
x_train, x_test, y_train, y_test = train_test_split(X,y, test_size = 0.1)

# For test :
# x_test.shape
# df.head()

# To divide to Train &  Test  part :
# X.shape: 395 ,6  ==> Output : means 6 col 395 row 
# y.shape: Output ==> 395

# Make our MODEL and then TEST  with our data x_train
model = LinearRegression() 

# Give to the model the TRAIN DATA  and say be train = fit
model.fit(x_train, y_train)

# now we should TEST and  understand its corretness(take data and check accuracy with x 
acc = model.score(x_test, y_test)
# Amount of accuracy 
print(acc)
# 82% correctness :we can predict the final score of one student 
# 0.8264046071944159 %     

# to show what is predicted by model  and what shouldve been , how much theyre close to each other 
predicted = model.predict(x_test)
for i in range(len(predicted)):
    print(f"Current Score is : {y_test[i]}, Predicted score: {predicted[i]}")
    print("*"*50)
    
# OutPut:
# Current Score is : 7, Predicte score: 7.3486597962563485
# **************************************************
# Current Score is : 13, Predicte score: 13.192187224625691
# **************************************************
# Current Score is : 5, Predicte score: 8.248406076534136   ==>noise 
# **************************************************
# Current Score is : 16, Predicte score: 16.819472148710354

# To find : y = mx + b
# To find  m  : in  y = m1x +b,m2x +b,m3x +b,m4x +b...+b , and equation of the liner 
model.coef_
# the weights m  for each feature:
# array([-0.00460173,  0.0249028 , -0.08335328, -0.03226121,  0.17617983,
#         0.88226034])

#  To get bias(y-intercept) : b
model.intercept_
# 0.6871826587283039

# To  Predict : 
model.predict([x_test[0]])
# array([14.49172583])

x_test[0]
# array([17, 32,  3,  3, 14, 13], dtype=int64)

# Final equation : y = mx + b
y = -0.00460173 * 17 + 0.0249028 * 32 + -0.08335328 *3 + -0.03226121*14 + 0.17617983 * 14 +  0.88226034* 13 + 0.6871826587283039
print("this is y :" , y)
# this is y : 14.640028108728304
#  y=14.640028108728304 is equal to  model.predict([x_test[0]])=14.49172583